package agent_test

import (
	"context"
	"os"
	"testing"

	"github.com/devalexandre/agno-golang/agno/agent"
	"github.com/devalexandre/agno-golang/agno/models"
	"github.com/devalexandre/agno-golang/agno/models/google/gemini"
	"github.com/devalexandre/agno-golang/agno/models/ollama"
	"github.com/devalexandre/agno-golang/agno/tools/exa"
	"github.com/devalexandre/agno-golang/agno/tools/toolkit"
)

func TestAgentPrintStreamResponse(t *testing.T) {
	apiKey := os.Getenv("GEMINI_API_KEY")
	exaApiKey := os.Getenv("EXA_API_KEY")
	optsClient := []models.OptionClient{
		models.WithID("gemini-2.0-flash"),
		models.WithAPIKey(apiKey),
	}
	geminiModel, err := gemini.NewGemini(optsClient...)
	if err != nil {
		panic(err)
	}
	agent, _ := agent.NewAgent(agent.AgentConfig{
		Context: context.Background(),
		Model:   geminiModel,
		Description: `

        You are Professor X-1000, a distinguished AI research scientist with expertise
        in analyzing and synthesizing complex information. Your specialty lies in creating
        compelling, fact-based reports that combine academic rigor with engaging narrative.

        Your writing style is:
        - Clear and authoritative
        - Engaging but professional
        - Fact-focused with proper citations
        - Accessible to educated non-specialists

		`,
		Instructions: `
		Begin by running 3 distinct searches to gather comprehensive information.
        Analyze and cross-reference sources for accuracy and relevance.
        Structure your report following academic standards but maintain readability.
        Include only verifiable facts with proper citations.
        Create an engaging narrative that guides the reader through complex topics.
        End with actionable takeaways and future implications
		`,
		ExpectedOutput: `
		A professional research report in markdown format:

		# {Compelling Title That Captures the Topic's Essence}

		## Executive Summary
		{Brief overview of key findings and significance}

		## Introduction
		{Context and importance of the topic}
		{Current state of research/discussion}

		## Key Findings
		{Major discoveries or developments}
		{Supporting evidence and analysis}

		## Implications
		{Impact on field/society}
		{Future directions}

		## Key Takeaways
		- {Bullet point 1}
		- {Bullet point 2}
		- {Bullet point 3}

		## References
		- [Source 1](link) - Key finding/quote
		- [Source 2](link) - Key finding/quote
		- [Source 3](link) - Key finding/quote

		---
		Report generated by Professor X-1000
		Advanced Research Systems Division
		Date: {current_date}
			`,
		Tools: []toolkit.Tool{
			exa.NewExaTool(exaApiKey),
		},
		Markdown:      true,
		Debug:         false,
		ShowToolsCall: true,
	})

	agent.PrintResponse("Research the latest developments in brain-computer interfaces.", true, true)
}

func TestAgentRunStream(t *testing.T) {
	apiKey := os.Getenv("GEMINI_API_KEY")
	exaApiKey := os.Getenv("EXA_API_KEY")
	optsClient := []models.OptionClient{
		models.WithID("gemini-2.0-flash"),
		models.WithAPIKey(apiKey),
	}
	geminiModel, err := gemini.NewGemini(optsClient...)
	if err != nil {
		panic(err)
	}
	agent, _ := agent.NewAgent(agent.AgentConfig{
		Context: context.Background(),
		Model:   geminiModel,
		Description: `

        You are Professor X-1000, a distinguished AI research scientist with expertise
        in analyzing and synthesizing complex information. Your specialty lies in creating
        compelling, fact-based reports that combine academic rigor with engaging narrative.

        Your writing style is:
        - Clear and authoritative
        - Engaging but professional
        - Fact-focused with proper citations
        - Accessible to educated non-specialists

		`,
		Instructions: `
		Begin by running 3 distinct searches to gather comprehensive information.
        Analyze and cross-reference sources for accuracy and relevance.
        Structure your report following academic standards but maintain readability.
        Include only verifiable facts with proper citations.
        Create an engaging narrative that guides the reader through complex topics.
        End with actionable takeaways and future implications
		`,
		ExpectedOutput: `
		A professional research report in markdown format:

		# {Compelling Title That Captures the Topic's Essence}

		## Executive Summary
		{Brief overview of key findings and significance}

		## Introduction
		{Context and importance of the topic}
		{Current state of research/discussion}

		## Key Findings
		{Major discoveries or developments}
		{Supporting evidence and analysis}

		## Implications
		{Impact on field/society}
		{Future directions}

		## Key Takeaways
		- {Bullet point 1}
		- {Bullet point 2}
		- {Bullet point 3}

		## References
		- [Source 1](link) - Key finding/quote
		- [Source 2](link) - Key finding/quote
		- [Source 3](link) - Key finding/quote

		---
		Report generated by Professor X-1000
		Advanced Research Systems Division
		Date: {current_date}
			`,
		Tools: []toolkit.Tool{
			exa.NewExaTool(exaApiKey),
		},
		Markdown:      true,
		Debug:         false,
		ShowToolsCall: true,
	})

	fullResponse := ""

	err = agent.RunStream("Research the latest developments in brain-computer interfaces.", func(chunk []byte) error {
		fullResponse += string(chunk)
		return nil
	})

	if err != nil {
		panic(err)
	}
	println("Response", fullResponse)

}

func TestSimpleAgentPrintStreamResponse(t *testing.T) {
	apiKey := os.Getenv("GEMINI_API_KEY")
	optsClient := []models.OptionClient{
		models.WithID("gemini-2.0-flash"),
		models.WithAPIKey(apiKey),
	}
	geminiModel, err := gemini.NewGemini(optsClient...)
	if err != nil {
		panic(err)
	}
	agent, _ := agent.NewAgent(agent.AgentConfig{
		Context:  context.Background(),
		Model:    geminiModel,
		Stream:   true,
		Markdown: true,
	})
	agent.PrintResponse("Tell me a story, about Brazil.", true, true)
}

func TestSimpleAgentPrintStreamResponseOllama(t *testing.T) {
	optsClient := []models.OptionClient{
		models.WithID("qwen2.5:1.5b"),
	}
	ollamaModel, err := ollama.NewOllamaChat(optsClient...)
	if err != nil {
		panic(err)
	}
	agent, _ := agent.NewAgent(agent.AgentConfig{
		Context:  context.Background(),
		Model:    ollamaModel,
		Stream:   true,
		Markdown: true,
	})
	agent.PrintResponse("Tell me a story, about Brazil.", true, true)
}

func TestAgentPrintStreamResponseOllama(t *testing.T) {
	apiKey := os.Getenv("GEMINI_API_KEY")
	exaApiKey := os.Getenv("EXA_API_KEY")
	optsClient := []models.OptionClient{
		models.WithID("qwen2.5:1.5b"),
		models.WithAPIKey(apiKey),
	}
	ollamaModel, err := ollama.NewOllamaChat(optsClient...)
	if err != nil {
		panic(err)
	}
	agent, _ := agent.NewAgent(agent.AgentConfig{
		Context: context.Background(),
		Model:   ollamaModel,
		Description: `

        You are Professor X-1000, a distinguished AI research scientist with expertise
        in analyzing and synthesizing complex information. Your specialty lies in creating
        compelling, fact-based reports that combine academic rigor with engaging narrative.

        Your writing style is:
        - Clear and authoritative
        - Engaging but professional
        - Fact-focused with proper citations
        - Accessible to educated non-specialists

		`,
		Instructions: `
		Begin by running 3 distinct searches to gather comprehensive information.
        Analyze and cross-reference sources for accuracy and relevance.
        Structure your report following academic standards but maintain readability.
        Include only verifiable facts with proper citations.
        Create an engaging narrative that guides the reader through complex topics.
        End with actionable takeaways and future implications
		`,
		ExpectedOutput: `
		A professional research report in markdown format:

		# {Compelling Title That Captures the Topic's Essence}

		## Executive Summary
		{Brief overview of key findings and significance}

		## Introduction
		{Context and importance of the topic}
		{Current state of research/discussion}

		## Key Findings
		{Major discoveries or developments}
		{Supporting evidence and analysis}

		## Implications
		{Impact on field/society}
		{Future directions}

		## Key Takeaways
		- {Bullet point 1}
		- {Bullet point 2}
		- {Bullet point 3}

		## References
		- [Source 1](link) - Key finding/quote
		- [Source 2](link) - Key finding/quote
		- [Source 3](link) - Key finding/quote

		---
		Report generated by Professor X-1000
		Advanced Research Systems Division
		Date: {current_date}
			`,
		Tools: []toolkit.Tool{
			exa.NewExaTool(exaApiKey),
		},
		Markdown:      true,
		Debug:         false,
		ShowToolsCall: true,
	})

	agent.PrintResponse("Research the latest developments in brain-computer interfaces.", true, true)
}
