package main

import (
	"context"
	"fmt"
	"log"
	"strings"

	"github.com/devalexandre/agno-golang/agno/agent"
	"github.com/devalexandre/agno-golang/agno/models"
	"github.com/devalexandre/agno-golang/agno/models/ollama"
)

// Example pre-hook: Validate input
func validateInputHook(ctx context.Context, input interface{}) error {
	fmt.Println("🔍 [PRE-HOOK] Validating input...")

	inputStr, ok := input.(string)
	if !ok {
		return fmt.Errorf("input must be a string")
	}

	if len(inputStr) < 3 {
		return fmt.Errorf("input must be at least 3 characters long")
	}

	if strings.Contains(strings.ToLower(inputStr), "forbidden") {
		return fmt.Errorf("input contains forbidden words")
	}

	fmt.Println("✅ [PRE-HOOK] Input validated successfully")
	return nil
}

// Example pre-hook: Log input
func logInputHook(ctx context.Context, input interface{}) error {
	fmt.Printf("📝 [PRE-HOOK] Logging input: %v\n", input)
	return nil
}

// Example post-hook: Validate output
func validateOutputHook(ctx context.Context, output *models.RunResponse) error {
	fmt.Println("🔍 [POST-HOOK] Validating output...")

	if output.TextContent == "" {
		return fmt.Errorf("output content is empty")
	}

	if len(output.TextContent) < 10 {
		return fmt.Errorf("output is too short")
	}

	fmt.Println("✅ [POST-HOOK] Output validated successfully")
	return nil
}

// Example post-hook: Transform output
func transformOutputHook(ctx context.Context, output *models.RunResponse) error {
	fmt.Println("🔄 [POST-HOOK] Transforming output...")

	// Add a footer to the response
	output.TextContent += "\n\n---\n✨ Generated by Agno Agent"

	fmt.Println("✅ [POST-HOOK] Output transformed successfully")
	return nil
}

// Example post-hook: Log output
func logOutputHook(ctx context.Context, output *models.RunResponse) error {
	fmt.Printf("📝 [POST-HOOK] Output length: %d characters\n", len(output.TextContent))
	fmt.Printf("📝 [POST-HOOK] Model used: %s\n", output.Model)
	return nil
}

func main() {
	ctx := context.Background()

	// Create an Ollama model
	model, err := ollama.NewOllamaChat(
		models.WithID("llama3.2:latest"),
		models.WithBaseURL("http://localhost:11434"),
	)
	if err != nil {
		log.Fatal(err)
	}

	fmt.Println("=== Agent with Hooks Example ===")
	fmt.Println("Demonstrates pre-hooks and post-hooks for validation and transformation\n")

	// Create agent with hooks
	agentWithHooks, err := agent.NewAgent(agent.AgentConfig{
		Context:      ctx,
		Model:        model,
		Name:         "HookedAssistant",
		Description:  "An AI assistant with validation hooks",
		Instructions: "You are a helpful AI assistant. Provide clear and concise answers.",
		Debug:        false,

		// Add hooks
		PreHooks: []func(context.Context, interface{}) error{
			validateInputHook,
			logInputHook,
		},
		PostHooks: []func(context.Context, *models.RunResponse) error{
			validateOutputHook,
			transformOutputHook,
			logOutputHook,
		},
	})
	if err != nil {
		log.Fatal(err)
	}

	// Test 1: Valid input
	fmt.Println("--- Test 1: Valid Input ---")
	response, err := agentWithHooks.Run("Hello, tell me about artificial intelligence")
	if err != nil {
		log.Printf("Error: %v\n", err)
	} else {
		fmt.Printf("\n📤 Response:\n%s\n", response.TextContent)
	}

	// Test 2: Invalid input (too short)
	fmt.Println("\n--- Test 2: Invalid Input (too short) ---")
	_, err = agentWithHooks.Run("Hi")
	if err != nil {
		fmt.Printf("❌ Expected error caught: %v\n", err)
	}

	// Test 3: Forbidden word
	fmt.Println("\n--- Test 3: Invalid Input (forbidden word) ---")
	_, err = agentWithHooks.Run("Tell me about forbidden topics")
	if err != nil {
		fmt.Printf("❌ Expected error caught: %v\n", err)
	}

	fmt.Println("\n✅ Hooks example completed!")
}
